### PR TITLE
fix(web): #76 fix +product button in Satisfaction

### LINKED ISSUE #76: The +product button in Satisfaction is not pre-filling the correct item in the new product
This was likely introduced by #60.

### PR DESCRIPTION
**Pull request by nils-keller-dev**
Closes #76 
These changes might be a bit controversial as I added functions to the `game-data-store.ts`.  
If you have other suggestions, let me know!

### CODE REVIEW

File: web/src/utils/factory-management/products.ts [hunk 1]
```diff
@@ -10,16 +10,8 @@ export const addProductToFactory = (
     recipe?: string,
   }
 ) => {
-  // In order to allow multiple products of the same product but using different recipes to be added, we need to generate a unique ID using the product's ID as well as the recipe ID.
-
-  let productId = ''
-
-  if (options.id && options.recipe) {
```
Comment (nils-keller-dev) [inline web/src/utils/factory-management/products.ts:17]: This was never the case as none of the function calls passed a `recipe`.  
I removed it as it broke my implementation otherwise

Comment (Maelstromeous) [reply web/src/utils/factory-management/products.ts:17]: Yeah this was the primary reason why the button was borked in the first place, I changed the expected data structure.

**Comment by Maelstromeous** [comment]
Tests are failing fyi

**Comment by Maelstromeous** [comment]
I like the refactor, recipe data is instringingly game data so yes absolutely makes sense to be in the store, then it is available anywhere in the code base. I do love the store concept!

**Review by Maelstromeous — CHANGES_REQUESTED** [review]
Tests

**Comment by nils-keller-dev** [comment]
I fixed the tests

**Comment by Maelstromeous** [comment]
One day sonarqube will work again!

**Comment by Maelstromeous** [comment]
Ok one thing I'd like you to test in the preview, please add a factory with duplicate products but different recipes. I believe using your implementation this might not work now, which would revert #9's fix.

**Comment by Maelstromeous** [comment]
Nevermind, just quickly tested it myself with two iron plates, works fine! Approved!

**Review by Maelstromeous — APPROVED** [review]
